name: 自动部署
on:
  push:
    branches:
      - main  # 或 'master'，根据实际情况选择
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v2
        with:
          ref: main
      - name: 安装Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.15.*"  # 根据实际情况选择Node.js版本
      - name: 部署Hexo
        run: |
          npm ci
          npm run clean
          npm run build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public